# Generated by Django 4.2.4 on 2023-10-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('En observacion', 'En observacion'), ('Atencion especial', 'Atencion especial'), ('Alta medica', 'Alta medica')], default='Alta medica', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(upload_to='pacientes/'),
        ),
    ]
